version: '3'
services:
  generator:
    build: .
    environment:
      URL_BASE: 'https://smartstage.caveon.com'
      ACCESS_TOKEN: '<access_token>'
      ITEM_ID: '5b8d7130-0279-4e92-9dd4-2cb6ff9a5943'
      NUM_INSTANCES: 1
    stdin_open: 'true'
    tty: 'true'
    volumes:
     - '.:/app'