version: '3'
services:
  generator:
    build: .
    environment:
      URL_BASE: 'https://smartstage.caveon.com'
      ACCESS_TOKEN: '<access_token>'
      ITEM_ID: '5177670f-d09e-4baf-9046-b253e35213b4'
      NUM_INSTANCES: 10
    stdin_open: 'true'
    tty: 'true'
    volumes:
     - '.:/app'